# SELECT O.ANIMAL_ID, O.NAME
# FROM ANIMAL_INS I, ANIMAL_OUTS O
# WHERE O.ANIMAL_ID NOT IN (
#     SELECT ANIMAL_ID
#     FROM ANIMAL_INS
# )
# GROUP BY ANIMAL_ID
# ORDER BY ANIMAL_ID

SELECT O.ANIMAL_ID, O.NAME
FROM ANIMAL_OUTS O
LEFT JOIN ANIMAL_INS I
ON O.ANIMAL_ID = I.ANIMAL_ID
WHERE SEX_UPON_INTAKE IS NULL